root: true

plugins:
  - jest
  - '@babel'

env:
  node: true
  jest/globals: true
  browser: true

parser: '@babel/eslint-parser'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  import/extensions: 0